global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: sinaap81@gmail.com
    from: noah.sanayco@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: noah.sanayco@gmail.com
    auth_identity: noah.sanayco@gmail.com
    auth_password: twbuenwhgymmjllv
    send_resolved: true


