groups:
- name: alert_rules
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: "critical"
    annotations:
      summary: "Endpoint {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."
  
  - alert: HostOutOfMemory
    expr: (node_memory_MemAvailable_bytes{job="node_exporter01"} / node_memory_MemTotal_bytes{job="node_exporter01"}) * 100 < 30
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Host out of memory (instance {{ $labels.instance }})"
      description: "Node memory is filling up (< 30% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

